// Auto-generated by generate-graph-data.py — do not edit manually.
// Regenerate after editing .md files or edges.jsonl.
const GRAPH_DATA = {
  "papers": [
    {
      "id": "paper:dosovitskiy2021_vit",
      "slug": "dosovitskiy2021_vit",
      "short": "ViT",
      "title": "An Image Is Worth 16x16 Words: Transformers for Image Recognition at Scale",
      "authors": [
        "Alexey Dosovitskiy",
        "Lucas Beyer",
        "Alexander Kolesnikov",
        "Dirk Weissenborn",
        "Xiaohua Zhai",
        "Thomas Unterthiner",
        "Mostafa Dehghani",
        "Matthias Minderer",
        "Georg Heigold",
        "Sylvain Gelly",
        "Jakob Uszkoreit",
        "Neil Houlsby"
      ],
      "year": 2021,
      "venue": "ICLR",
      "arxiv": "2010.11929",
      "tags": [
        "vision-transformer",
        "image-classification",
        "self-attention",
        "patch-embedding",
        "scaling"
      ],
      "nodeColor": "#3fb950",
      "thesis": "A pure Transformer architecture applied directly to sequences of image patches can achieve state-of-the-art image classification when pre-trained at sufficient scale, outperforming convolutional networks with lower pre-training cost.",
      "sections": {
        "One-line thesis": "A pure Transformer architecture applied directly to sequences of image patches can achieve state-of-the-art image classification when pre-trained at sufficient scale, outperforming convolutional networks with lower pre-training cost.",
        "Assumptions": "- Sufficient pre-training data is available (at least 14M images) — the model does not generalize well on small data\n- Patch size and position embedding interpolation are sufficient spatial inductive bias; the model assumes 2D structure can be learned from data\n- Standard Transformer architecture transfers directly from NLP to vision with minimal modification\n之前的视觉问题无论如何解决不了对CNN的依赖，研究证明对CNN的依赖不是必要的（直接使用序列方法）。在大量数据上进行预训练并迁移到多个中型或小型图像识别基准时表现很好。\n在小的数据集上表现要略低于ResNets，作者的观点是因为这缺乏了某些先验假设\nViT挑战了CNN的“归纳偏置”。简单来说，**归纳偏置就是模型为了让学习问题变得可行，而提前内置在算法中的“先验知识”或“默认假设”。**CNN的先验知识就是假设图像具有**局部性**和**平移等变性**\n这也是为什么ViT在小尺寸表现不好（作者认为小尺寸更关注局部信息，这对全局处理的架构没有很大帮助）但是扩展到大尺寸的图片表现优于传统CNN",
        "Problem / Gap": "The dominant approach in computer vision relied on convolutional architectures (CNNs). While Transformers had become standard in NLP, their application to vision was limited to augmenting CNNs or replacing specific components. Prior attempts at pure self-attention for images either used complex engineering for efficient implementation or underperformed on mid-sized datasets. The question was whether the scalability of Transformers could overcome the lack of CNN-like inductive biases (translation equivariance, locality) in vision.",
        "Method": "ViT splits an image into fixed-size patches (e.g., 16x16), linearly embeds each patch, adds position embeddings, and feeds the resulting sequence to a standard Transformer encoder. A learnable [CLS] token appended to the sequence serves as the image representation for classification. The model uses standard Transformer blocks (multi-head self-attention, MLP, LayerNorm, residual connections). ViT intentionally minimizes vision-specific modifications — the key inductive biases are only at patch extraction and position embedding interpolation during fine-tuning. A hybrid variant uses CNN feature maps as input patches instead of raw pixels.",
        "Key Results": "- Pre-trained on ImageNet-21k (14M images) or JFT-300M (303M images), ViT matches or beats state-of-the-art CNNs on multiple benchmarks\n- Best model: 88.55% on ImageNet, 90.72% on ImageNet-ReaL, 94.55% on CIFAR-100, 77.63% on VTAB (19 tasks)\n- ViT requires substantially less computational resources to pre-train than comparable CNNs\n- Performance scales with dataset size — on mid-sized datasets (ImageNet-1k) ViT underperforms ResNets of comparable size without strong regularization, but on large datasets the gap reverses\n- Self-supervised pre-training (masked patch prediction) shows promising initial results",
        "Limitations / Failure Modes": "- Requires large-scale pre-training data to outperform CNNs; on small data it underperforms due to lack of built-in inductive biases\n- Quadratic self-attention cost in sequence length limits high-resolution image processing\n- Position embedding interpolation at higher resolutions during fine-tuning is a heuristic\n- Less parameter-efficient than CNNs for small to medium data regimes\n- No built-in translation equivariance — the model must learn spatial relationships from scratch",
        "Reusable Ingredients": "- Patch-based image tokenization (16x16 patches as visual \"words\")\n- Pre-trained [CLS] token representation for transfer learning\n- Hybrid CNN+Transformer design for leveraging feature maps\n- 2D interpolation of position embeddings for variable-resolution fine-tuning\n- Scalable proof that large-scale training trumps inductive bias",
        "Open Questions": "- Can ViT benefit from more vision-specific inductive biases without losing scalability?\n- How does ViT compare on dense prediction tasks (detection, segmentation) without architectural modifications?\n- What is the optimal patch size trade-off between performance and computational cost?",
        "Claims": "",
        "Relevance to This Project": "Foundational architecture for modern vision-language models — both CLIP and BLIP-2 use ViT as a backbone image encoder. Understanding ViT is essential for any VLM research."
      },
      "connections": [
        {
          "type": "extended_by",
          "target": "CLIP",
          "targetId": "paper:radford2021_clip",
          "text": "CLIP uses ViT as one of its image encoder backbones (Section 2.3: image encoders include ViT and ResNet)"
        },
        {
          "type": "extended_by",
          "target": "BLIP-2",
          "targetId": "paper:li2023_blip2",
          "text": "BLIP-2 uses ViT-based frozen image encoders (e.g., ViT-L/14) as visual backbones (Section 3.1)"
        }
      ]
    },
    {
      "id": "paper:radford2021_clip",
      "slug": "radford2021_clip",
      "short": "CLIP",
      "title": "Learning Transferable Visual Models From Natural Language Supervision",
      "authors": [
        "Alec Radford",
        "Jong Wook Kim",
        "Chris Hallacy",
        "Aditya Ramesh",
        "Gabriel Goh",
        "Sandhini Agarwal",
        "Girish Sastry",
        "Amanda Askell",
        "Pamela Mishkin",
        "Jack Clark",
        "Gretchen Krueger",
        "Ilya Sutskever"
      ],
      "year": 2021,
      "venue": "arXiv",
      "arxiv": "2103.00020",
      "tags": [
        "contrastive-learning",
        "vision-language",
        "zero-shot",
        "multi-modal",
        "image-text"
      ],
      "nodeColor": "#58a6ff",
      "thesis": "Pre-training an image encoder and text encoder jointly with a contrastive objective on 400 million (image, text) pairs yields transferable visual representations that enable zero-shot classification on diverse downstream tasks without task-specific training.",
      "sections": {
        "One-line thesis": "Pre-training an image encoder and text encoder jointly with a contrastive objective on 400 million (image, text) pairs yields transferable visual representations that enable zero-shot classification on diverse downstream tasks without task-specific training.",
        "Problem / Gap": "Computer vision systems were traditionally trained to predict fixed predetermined object categories, limiting their generality. Learning from raw text about images was a promising direction but had demonstrated much lower performance than supervised approaches. Prior attempts at natural language supervision for vision either used small datasets (MS-COCO, Visual Genome, YFCC100M) or complex generative objectives; scaling to web-scale data was underexplored.",
        "Method": "CLIP (Contrastive Language-Image Pre-training) trains an image encoder and a text encoder jointly to predict correct pairings in a batch of (image, text) examples. The contrastive objective maximizes cosine similarity between matched image-text pairs while minimizing it for mismatched pairs. Both encoders can be various architectures (ViT or ResNet for images; Transformer for text). After pre-training, natural language is used to reference visual concepts, enabling zero-shot transfer — the text encoder synthesizes a classifier by embedding class names/descriptions, and prediction is done by selecting the highest similarity score. Training uses a dataset of 400M (image, text) pairs called WIT (WebImageText).",
        "Key Results": "- Zero-shot CLIP matches ResNet-50 accuracy on ImageNet without using any of its 1.28M training examples\n- Competitive with fully supervised baselines on over 30 datasets spanning OCR, action recognition, geo-localization, fine-grained classification\n- Zero-shot CLIP is much more robust than equivalent-accuracy supervised ImageNet models\n- Transfer performance is a smoothly predictable function of compute\n- Linear-probe CLIP outperforms the best publicly available ImageNet model while being more computationally efficient",
        "Assumptions": "- Contrastive learning is sufficient for vision-language alignment (more efficient than generative/predictive approaches — 4x more efficient than bag-of-words prediction, 12x more than transformer language model)\n- Web-scale data (400M image-text pairs) covers a sufficiently broad set of visual concepts\n- Natural language is an effective supervision signal for learning visual representations",
        "Limitations / Failure Modes": "- Zero-shot performance on fine-grained or specialized tasks (e.g., medical imaging, satellite imagery) can be poor if the concepts are not well-represented in WIT\n- The contrastive objective may miss finer-grained visual understanding that generative objectives capture\n- Requires careful engineering to scale contrastive learning to hundreds of millions of examples\n- Text encoder quality depends on the diversity and quality of captions in the training data\n- Can exhibit social biases present in web-crawled data",
        "Reusable Ingredients": "- Contrastive image-text pre-training paradigm (now standard in VLM research)\n- Dual-encoder architecture for separate image and text representation\n- Zero-shot transfer via natural language class descriptors\n- Text-prompt engineering for downstream task adaptation\n- WIT dataset construction methodology (500K query-based balanced collection)",
        "Open Questions": "- How much further can CLIP-style models scale with more data and compute?\n- Can generative objectives complement contrastive learning for better fine-grained understanding?\n- How to improve zero-shot performance on out-of-distribution or rare visual concepts?",
        "Claims": "",
        "Relevance to This Project": "CLIP is the foundational vision-language model that enables zero-shot transfer. BLIP-2 builds directly on CLIP-style pre-trained image encoders. CLIP's contrastive objective is a key component in modern VLMs."
      },
      "connections": [
        {
          "type": "extends",
          "target": "ViT",
          "targetId": "paper:dosovitskiy2021_vit",
          "text": "CLIP uses ViT as one of its image encoder backbones (Section 2.3: image encoders include ViT and ResNet)"
        },
        {
          "type": "extended_by",
          "target": "BLIP-2",
          "targetId": "paper:li2023_blip2",
          "text": "BLIP-2 uses frozen CLIP image encoders and builds on contrastive vision-language pre-training (Section 2.2, Section 3)"
        }
      ]
    },
    {
      "id": "paper:li2023_blip2",
      "slug": "li2023_blip2",
      "short": "BLIP-2",
      "title": "BLIP-2: Bootstrapping Language-Image Pre-training with Frozen Image Encoders and Large Language Models",
      "authors": [
        "Junnan Li",
        "Dongxu Li",
        "Silvio Savarese",
        "Steven Hoi"
      ],
      "year": 2023,
      "venue": "arXiv",
      "arxiv": "2301.12597",
      "tags": [
        "vision-language",
        "q-former",
        "frozen-encoders",
        "llm",
        "multi-modal",
        "efficient-pretraining"
      ],
      "nodeColor": "#da3633",
      "thesis": "BLIP-2 proposes a generic and compute-efficient vision-language pre-training strategy that bootstraps from frozen pre-trained image encoders and frozen LLMs via a lightweight Querying Transformer (Q-Former), achieving state-of-the-art results with far fewer trainable parameters.",
      "sections": {
        "One-line thesis": "BLIP-2 proposes a generic and compute-efficient vision-language pre-training strategy that bootstraps from frozen pre-trained image encoders and frozen LLMs via a lightweight Querying Transformer (Q-Former), achieving state-of-the-art results with far fewer trainable parameters.",
        "Problem / Gap": "Vision-language pre-training (VLP) had become increasingly prohibitive due to end-to-end training of ever-larger models. Prior methods required expensive end-to-end training of both vision and language components. While leveraging frozen unimodal pre-trained models (image encoders, LLMs) was appealing, aligning their feature spaces — especially when the LLM has never seen images — remained a key challenge. Existing modular approaches (Frozen, Flamingo) used only image-to-text generation loss, which proved insufficient to bridge the modality gap.",
        "Method": "BLIP-2 introduces a **Querying Transformer (Q-Former)** — a lightweight 188M parameter transformer with 32 learnable query tokens that acts as an information bottleneck between a frozen image encoder and a frozen LLM. The pre-training has two stages:\n\n1. **Stage 1 — Vision-Language Representation Learning**: Q-Former is connected to a frozen image encoder and jointly optimized with three objectives: Image-Text Contrastive Learning (ITC), Image-grounded Text Generation (ITG), and Image-Text Matching (ITM). Different attention masking strategies control query-text interaction.\n\n2. **Stage 2 — Vision-to-Language Generative Learning**: The Q-Former output is connected to a frozen LLM (OPT or FlanT5). The Q-Former is trained so its output visual representations can be interpreted by the LLM for text generation.\n\nThe query bottleneck (32×768) forces the model to extract visual information most relevant to the text, making the approach highly compute-efficient.",
        "Key Results": "- Outperforms Flamingo80B by 8.7% on zero-shot VQAv2 with **54x fewer trainable parameters**\n- State-of-the-art on various vision-language tasks: visual question answering, image captioning, image-text retrieval\n- Demonstrates zero-shot image-to-text generation following natural language instructions (visual knowledge reasoning, visual conversation)\n- Works with both decoder-only LLMs (OPT) and encoder-decoder LLMs (FlanT5)\n- Generic framework — can harvest more advanced unimodal models for better VLP performance",
        "Assumptions": "- Frozen pre-trained unimodal models (image encoders and LLMs) provide sufficiently high-quality features that can be aligned through a lightweight bottleneck\n- The Q-Former's 32 learnable queries are sufficient to capture all visual information relevant to text\n- Two-stage pre-training (representation learning → generative learning) is necessary and sufficient for effective modality alignment\n- Catastrophic forgetting is avoided by keeping unimodal models frozen",
        "Limitations / Failure Modes": "- The Q-Former adds architectural complexity and an extra pre-training phase compared to end-to-end methods\n- Performance is upper-bounded by the frozen image encoder and LLM quality — better unimodal models are needed for gains\n- The fixed 32-query bottleneck may limit information flow for complex visual understanding tasks\n- Two-stage pre-training requires careful scheduling and hyperparameter tuning\n- Dependence on availability of high-quality frozen pre-trained unimodal models",
        "Reusable Ingredients": "- Q-Former architecture with learnable query tokens as an information bottleneck between vision and language\n- Two-stage bootstrapping strategy (representation learning → generative learning)\n- Three-objective joint optimization (ITC + ITG + ITM) with attention masking\n- Generic framework for composing any frozen image encoder with any frozen LLM\n- Computationally efficient VLP recipe (SOTA with far fewer trainable parameters)",
        "Open Questions": "- How does the 32-query bottleneck scale with more complex vision-language tasks?\n- Can the two-stage pre-training be unified into a single stage?\n- How does Q-Former compare with cross-attention layers (Flamingo) at extreme scales?",
        "Claims": "",
        "Relevance to This Project": "BLIP-2 represents the state-of-the-art in efficient vision-language pre-training, directly relevant to VLM research. It shows how to effectively combine frozen vision encoders (like ViT, CLIP) with LLMs — a paradigm central to modern VLM design."
      },
      "connections": [
        {
          "type": "extends",
          "target": "CLIP",
          "targetId": "paper:radford2021_clip",
          "text": "BLIP-2 uses frozen CLIP image encoders and builds on contrastive vision-language pre-training (Section 2.2, Section 3)"
        },
        {
          "type": "extends",
          "target": "ViT",
          "targetId": "paper:dosovitskiy2021_vit",
          "text": "BLIP-2 uses ViT-based frozen image encoders (e.g., ViT-L/14) as visual backbones (Section 3.1)"
        }
      ]
    }
  ],
  "edges": [
    {
      "from": "paper:radford2021_clip",
      "to": "paper:dosovitskiy2021_vit",
      "type": "extends",
      "evidence": "CLIP uses ViT as one of its image encoder backbones (Section 2.3: image encoders include ViT and ResNet)",
      "added": "2026-05-29T08:26:38Z"
    },
    {
      "from": "paper:li2023_blip2",
      "to": "paper:radford2021_clip",
      "type": "extends",
      "evidence": "BLIP-2 uses frozen CLIP image encoders and builds on contrastive vision-language pre-training (Section 2.2, Section 3)",
      "added": "2026-05-29T08:26:39Z"
    },
    {
      "from": "paper:li2023_blip2",
      "to": "paper:dosovitskiy2021_vit",
      "type": "extends",
      "evidence": "BLIP-2 uses ViT-based frozen image encoders (e.g., ViT-L/14) as visual backbones (Section 3.1)",
      "added": "2026-05-29T08:26:39Z"
    }
  ]
};
